#!/bin/bash

echo "🔍 Testing Auth State Management"
echo "=================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "📋 Test Checklist:"
echo ""
echo "1️⃣ Auth Context Check"
echo "   ✅ checkAuth() reads from localStorage on app load"
echo "   ✅ Sets user state if token + role exist"
echo "   ✅ setIsLoading(false) always called"
echo ""
echo "2️⃣ Login Function Check"
echo "   ✅ Calls API to get token + role"
echo "   ✅ Stores in localStorage"
echo "   ✅ Updates user state BEFORE redirect"
echo "   ✅ Returns success with role"
echo ""
echo "3️⃣ ProtectedRoute Check"
echo "   ✅ Shows spinner while isLoading === true"
echo "   ✅ Redirects to /login if !isLoggedIn"
echo "   ✅ Checks allowedRoles"
echo "   ✅ Renders children if authorized"
echo "   ✅ Uses useRef to prevent multiple redirects"
echo ""
echo "4️⃣ Login Page Check"
echo "   ✅ Uses useAuth() hook"
echo "   ✅ Calls login() from context (not direct API)"
echo "   ✅ Waits for state update (100ms delay)"
echo "   ✅ Then calls router.replace()"
echo "   ✅ Auto-redirects if already logged in"
echo ""
echo "=================================="
echo ""
echo "🧪 Manual Testing Steps:"
echo ""
echo "${YELLOW}Step 1: Clear localStorage${NC}"
echo "   - Open browser console"
echo "   - Run: localStorage.clear()"
echo ""
echo "${YELLOW}Step 2: Visit login page${NC}"
echo "   - Go to: http://localhost:3000/login"
echo "   - Should show login form (not spinner)"
echo ""
echo "${YELLOW}Step 3: Check console logs${NC}"
echo "   Should see:"
echo "   [AUTH] Checking localStorage for existing session..."
echo "   [AUTH] Token: ✗ Missing"
echo "   [AUTH] No valid session in localStorage"
echo "   [AUTH] Initial auth check complete"
echo ""
echo "${YELLOW}Step 4: Login as admin${NC}"
echo "   - Email: admin@gmail.com"
echo "   - Password: admin"
echo "   - Click Sign In"
echo ""
echo "${YELLOW}Step 5: Watch console logs${NC}"
echo "   Should see (in order):"
echo "   [LOGIN PAGE] Starting login for: admin@gmail.com"
echo "   [AUTH] Login attempt for: admin@gmail.com"
echo "   [API] Login request for: admin@gmail.com"
echo "   [API] Storing auth data..."
echo "   [AUTH] Login successful - Role: admin"
echo "   [AUTH] User state updated: {...}"
echo "   [LOGIN PAGE] Login successful! Role: admin"
echo "   [LOGIN PAGE] Redirecting to: /admin/dashboard"
echo ""
echo "${YELLOW}Step 6: Verify redirect happens${NC}"
echo "   - Should redirect to /admin/dashboard within 1 second"
echo "   - Should NOT see infinite spinner"
echo "   - Should NOT redirect back to /login"
echo ""
echo "${YELLOW}Step 7: Check ProtectedRoute logs${NC}"
echo "   Should see:"
echo "   [PROTECTED ROUTE] {isLoading: false, isLoggedIn: true, userRole: 'admin', ...}"
echo "   [PROTECTED ROUTE] Access granted ✓"
echo ""
echo "${YELLOW}Step 8: Reload page${NC}"
echo "   - Press Cmd+R / Ctrl+R"
echo "   - Should see brief spinner"
echo "   - Then dashboard loads"
echo "   - Should see:"
echo "     [AUTH] Checking localStorage for existing session..."
echo "     [AUTH] Token: ✓ Present"
echo "     [AUTH] Restored user from localStorage: admin@gmail.com"
echo ""
echo "=================================="
echo ""
echo "❌ Common Issues to Check:"
echo ""
echo "1. ${RED}Infinite spinner after login${NC}"
echo "   → Check: isLoading stuck at true?"
echo "   → Fix: Ensure setIsLoading(false) always called"
echo ""
echo "2. ${RED}Redirect loop${NC}"
echo "   → Check: ProtectedRoute shows isLoggedIn: false?"
echo "   → Fix: Ensure login() updates user state"
echo "   → Fix: Ensure localStorage has token + role"
echo ""
echo "3. ${RED}401 errors${NC}"
echo "   → This is OK for now - we removed /auth/verify"
echo "   → Auth is localStorage-based"
echo ""
echo "4. ${RED}State not persisting${NC}"
echo "   → Check localStorage has: token, role, user_id, user_name, user_email"
echo "   → Run: Object.keys(localStorage)"
echo ""
echo "=================================="
echo ""
echo "✅ Success Criteria:"
echo "   - Login completes in < 2 seconds"
echo "   - Redirects to correct dashboard"
echo "   - No infinite spinner"
echo "   - No redirect loop"
echo "   - Page reload preserves login state"
echo "   - Console shows clear state transitions"
echo ""
echo "🚀 Start testing: http://localhost:3000/login"
